language: cpp
dist: trusty
os:
  - linux
script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON
  - make -j2
  - cd test
  - ctest
  - bash <(curl -s https://codecov.io/bash)