nguage: cpp
dist: trusty
compiler:
  - gcc
os:
  - linux
before_install:
  - sudo pip install codecov
script:
  - bash build_tests.sh
  - bash run_tests.sh
  - bash build_examples.sh
  - bash run_examples.sh
  - codecov
env:
  global:
    - MAKEFLAGS="-j 2"
