version: '{build}'
image: Ubuntu
install:
- sh: git submodule update --init --recursive
build_script:
- sh: >-
    mkdir build

    cd build
    
    cmake .. -DBUILD_TESTS=ON
    
    make
    
    cd test

    ctest